### ISSUE TITLE
callback function needs to support carrying parameters

### ISSUE THREAD

**Issue by Zhengqbbb** [aaronkirkham/vue-gamepad#10]
Hello, I think the callback function needs to support carrying parameters

```
   <button v-gamepad:button-a="pressed('A-button')"></button>

    pressed(a) {
          this.text = 'You are pressing the button!';
          console.log(`press`, a);
       },
```
it will throw error

case me need to do：
```
<button v-gamepad:button-a="()=>pressed('A-button')">{{ text }}</button>
```

**Comment by aaronkirkham** [comment]
Hey!

If I remember correctly, this is not possible in Vue 2.x directives (not tested in 3.x) as the value would be evaluated inline. (custom directives behave a little different to default "@" directives)

Please see: https://github.com/vuejs/vue/issues/5588

The official preferred solution is (as you said):
```vue
<button v-gamepad:button-a="()=>pressed('A-button')">{{ text }}</button>
```

Maybe as an alternative we could support some kind of global handler which would pass information about the button press instead, but not absolutely sure this is the right way to go here.

Example:
```vue
<button v-gamepad.pressed="callback"></button>
```

```js
methods: {
  callback(button) {
    button.name; // button-a
  },
},
```

**Comment by Zhengqbbb** [comment]
> Hey!
> 
> If I remember correctly, this is not possible in Vue 2.x directives (not tested in 3.x) as the value would be evaluated inline. (custom directives behave a little different to default "@" directives)
> 
> Please see: [vuejs/vue#5588](https://github.com/vuejs/vue/issues/5588)
> 
> The official preferred solution is (as you said):
> 
> ```
> <button v-gamepad:button-a="()=>pressed('A-button')">{{ text }}</button>
> ```
> 
> Maybe as an alternative we could support some kind of global handler which would pass information about the button press instead, but not absolutely sure this is the right way to go here.
> 
> Example:
> 
> ```
> <button v-gamepad.pressed="callback"></button>
> ```
> 
> ```js
> methods: {
>   callback(button) {
>     button.name; // button-a
>   },
> },
> ```

**Comment by Zhengqbbb** [comment]
Thank you, but there is an optimization item I think is necessary:
**Add axes to the parameters**.This makes me need to get it like this

```js
  omniDirectionalControl() {
      const p1GamepadIndex = 0;
      const p1Gamepad = navigator.getGamepads()[p1GamepadIndex];
      if (p1Gamepad.axes) {
        const axesOffset = calAxes(p1Gamepad.axes);
        this.$emit('callOperate', 'joystickControl', axesOffset);
        this.callActiveClassByAxes(axesOffset);
      }
    },
```

**Comment by aaronkirkham** [comment]
I could pass the `Gamepad` object in the event handler arguments, which would be a reference to the gamepad that triggered the event?

```js
<button v-gamepad.pressed="callback"></button>

methods: {
  callback(gamepad) {
    gamepad.axes; // "gamepad" would be the same as navigator.getGamepads()[index]
  },
},
```

**Comment by Zhengqbbb** [comment]
> I could pass the `Gamepad` object in the event handler arguments, which would be a reference to the gamepad that triggered the event?

yep.
I saw in your Vue3.0 next branch that this way is correct. thx
